### ISSUE TITLE
Run inproc without an input shell?

### ISSUE THREAD

**Issue by sid-kap** [Gabriel439/Haskell-Turtle-Library#114]
I don't know much about UNIX shells, but from my understanding, it seems like there is a semantic difference between running a command with an empty input shell/pipe, and running a command with no input shell/pipe.

Here's an example:

Suppose `test.tcl` contains:
```tcl
#!/usr/bin/expect

set timeout 2000000

expect_after {
    timeout {
        puts "----> timeout <----\r"
        exit
    }
}

spawn echo hi

expect "hi"
```

If you run `expect test.tcl` (or if you run `system "expect test.tcl"` in ghci, after importing `System.Process`), you get
```
spawn echo hi
hi
```
(You can see that the command to be run (`spawn echo hi`) is printed, followed by the actual output of the command (`hi`).)

If you run `echo -n | expect test.tcl` (or if you run `view (inproc "expect" ["test.tcl"] empty)` in ghci after importing `Turtle`), you get
```
spawn echo hi
```

I'm not sure exactly what's going on here, but it seems like the expect program acts differently between when it has an (empty) input pipe and when it has no input pipe.

Is there a way to run a process with no input pipe in Turtle? Or should I just use `liftIO (system "expect test.tcl")` in this situation? (Note that this strategy doesn't accomplish exactly what I want: `liftIO (system "expect test.tcl")` has type `Shell ExitCode`, not `Shell Text`.)

**Comment by Gabriel439** [comment]
Yeah, `turtle` tries to provide a easy-to-use subset of the full `process` library's API and I think this is one of those cases where the `turtle` API is not general enough to handle your need because there is no utility in the library that doesn't open the standard input handle.  You may have to use the `process` API directly to get your desired behavior with either `System.Process.readProcess` or `System.Process.readProcessWithExitCode`.

**Comment by sid-kap** [comment]
That makes sense. Thanks!

**Comment by Gabriel439** [comment]
You're welcome!
