### ISSUE TITLE
Current dir with forks (sub shells)

### ISSUE THREAD

**Issue by yogsototh** [Gabriel439/Haskell-Turtle-Library#116]
Env variable like current dir doesn't duplicate with fork.

Typically:

~~~
main :: IO ()
main = do
    orig <- pwd
    mkdir "foo"
    mkdir "bar"
    runManaged $ do
       foo <- fork $ do
           cd "foo"
           forever $ pwd >>= print >> sleep 1
       liftIO (cd orig)
       bar <- fork $ do
           cd "bar"
           sleep 0.5
           forever $ pwd >>= print >> sleep 1
       liftIO (wait foo >> wait bar)
~~~

Actually prints:

~~~
FilePath "/Users/me/dev/foo"
FilePath "/Users/me/dev/bar"
FilePath "/Users/me/dev/bar"
FilePath "/Users/me/dev/bar"
FilePath "/Users/me/dev/bar"
FilePath "/Users/me/dev/bar"
FilePath "/Users/me/dev/bar"
FilePath "/Users/me/dev/bar"
FilePath "/Users/me/dev/bar"
FilePath "/Users/me/dev/bar"
FilePath "/Users/me/dev/bar"
FilePath "/Users/me/dev/bar"
FilePath "/Users/me/dev/bar"
...
~~~

I would like to find a way to have multiple "current dir". One for each fork.

Ideally I would like to have a way to launch "sub shells".

**Comment by Gabriel439** [comment]
I might be wrong, but as far as I can tell this isn't possible within a single Haskell program in the way that you have in mind.

Here is my rough understanding: any given process can only have one current working directory associated with that process, no matter how many threads that program uses (even OS threads).  The only way to get multiple working directories is to have multiple processes.  However, in order to take a segment of Haskell code and run it within a separate process you need to separately compile that code and then invoke it using a subprocess runner (i.e. `proc` or `shell`, for example, which do create new processes).  As far as I know, there is no way to take Haskell code within a program and embed it within a separate process.

**Comment by Gabriel439** [comment]
I'll go ahead and close this for now, but if you have any other questions about this feel free to ask.
