### ISSUE TITLE
File-path-heavy scripts are a chore

### ISSUE THREAD

**Issue by 3noch** [Gabriel439/Haskell-Turtle-Library#132]
My first "serious" turtle script downloads GHCJS snapshot sdists and reformats them for use with stack: https://gist.github.com/3noch/4696feff5c602e126681.

However, this was a real chore to write. I think that it is due to a) `tar` having a confusing interface for archiving folders, b) not knowing how to write effectful folds..., and *especially* c) doing any string munging on `FilePath`s is terribly verbose.

Since this is my first script, I imagine I'm missing some key ways to improve this? I'd love to hear feedback, and perhaps use this as a nudge to start using a better filepath library.

**Comment by 3noch** [comment]
Also, having something that composes `echo` and `format` would be very nice.

**Comment by 3noch** [comment]
Furthermore, let me put in a vote for throwing on `ExitFailure`. I spent an hour debugging the script only to find that my `tar` command was failing and I didn't know it!

**Comment by Gabriel439** [comment]
There are two things I can do to make things more ergonomic.

First, I can add this utility to `Turtle.Prelude`:

```haskell
printf = echo . format
```

Second, I can add this short-hand synonym for `format`:

```haskell
fmt = format
```

However, I still plan to keep `FilePath` a separate type from `Text` so you will still need to do some conversion.  All I can do is shorten the number of characters for the conversion function.

To write an effectful fold, you need to provide three functions:

```haskell
-- A starting state
begin :: IO x

-- The step function
step :: x -> a -> IO x

-- The final step when all input elements are exhausted
done :: x -> IO b
```

... and then package them in a `FoldM`, like this:

```haskell
effectfulFold :: FoldM IO a b
effectfulFold = FoldM step begin done
```

... and then you can apply that effectful fold to any `Shell` stream by using:

```haskell
foldIO someStream effectfulFold
```

I can also add exit-throwing variations on `proc` and `shell` so that you don't have to worry about ignoring exit codes.

I can also add a Haskell-native `tar` to `turtle` by adding the `tar` library as a dependency.

If you really want to improve the state of `FilePath` in Haskell, my recommendation is to pick up this GHC proposal and take it across the finish line:

https://ghc.haskell.org/trac/ghc/wiki/Proposal/AbstractFilePath

It's better to improve the standard `FilePath` than to fragment the `FilePath` ecosystem even further.

**Comment by Gabriel439** [comment]
Also, going through your script in more detail I have a couple more comments:

* I can add a `Format` specifier for `UTCTime`s.  I've actually been using this in my own internal code at Twitter but I forgot to add it to `turtle`.
* The fact that `wreq` takes a `String` argument for `get` is a problem with `wreq`.  `wreq` already has a dependency on the `text` library (which is by the same author) so it doesn't make a lot of sense to expose a `String` interface.  You should open an issue against `wreq` to fix that if you think that `Text`-to-`String` conversion was too cumbersome
* You don't need to parenthesize the arguments to a lambda.  For example, this:

```haskell
with (writeonly tempfile) $ \(temphandle) ->
    hPut temphandle (r ^. responseBody)
```

... can be written as:

```haskell
with (writeonly tempfile) $ \temphandle ->
    hPut temphandle (r ^. responseBody)
```

The only time you need to parenthesize a variable bound by a lambda is if you are doing a destructuring pattern match on the bound variable, like this:

```haskell
example = \(Point x y) -> ...
```

Other than that the script looks pretty idiomatic to me.

**Comment by 3noch** [comment]
> `printf = echo . format`
Perfect!

I understand the tension to leave out trivial "ergonomic" improvements from a library. Still, in a scripting language, it's not common to build up a set of common tools and terms that can be shared across scripts, so it does seem wise to put more things like this directly into turtle.

> `fmt = format`
Not bad... I'm not sure I'd use it. I'd be more likely to wrap `format` with other more specific functions. I likely will do that for this script.

>  I still plan to keep `FilePath` a separate type from `Text`
Great. I wouldn't dream of doing otherwise.

However, perhaps Turtle could have a bit better support for doing FilePath-related things. For example, I wanted to use `find` to search for a directory that matched a pattern. But alas, `find` only works on files. So I had to use `ls` and cobble together pattern match directly on `Text`. Alternatively, I could have just listed only directories, but that meant writing an effectful fold which I didn't yet understand. (Thanks for describing how!) Do you have ideas for how to improve my script in this area, or Turtle itself?

> I can also add exit-throwing variations on proc and shell so that you don't have to worry about ignoring exit codes.
This would indeed be the best of both worlds. People can choose which flavor they like.

> I can also add a Haskell-native tar to turtle by adding the tar library as a dependency.
I like it, though it does seem a bit heavy-weight.

> I can add a Format specifier for `UTCTime`s.
Awesome.

> a problem with `wreq`
Agreed. I will file, but I doubt it will be considered since that's a major API change at this point.
Can you recommend other downloading tools? This seems like something that could be built in to Turtle.

----
Having Turtle able to natively do both basic HTTP-client activities and deal with packed and/or compressed archives would certainly be extremely convenient, especially considering that these activities are particularly hard to do in a cross-platform way (I'm looking at you, Windows).

Still, it seems to me that both of these would incur fairly heavy dependencies. Perhaps it's worth adding a `turtle-extra` package that can do other common "shell-like" tasks, but still allows people to use the thinner core that you've built without incurring those dependencies?

**Comment by teh** [comment]
To add a data point: I've just written the first semi-serious Turtle code. The library is great joy but file paths are slightly painful. A lot of functions start of like this: 

```
    let path = workspacePath T.</> (T.fromText ("pr-" <> branch))
    let pathStr = T.format T.fp path
```

because I need path both as a `FilePath` and as `Text` when running `proc`. Not sure how `AbstractFilePath` would fix that - maybe it's an inherent problem with having a stringly-typed filesystem.

Throwing-on-exit `proc` variants would be a great addition. Then I could write code like bash's `set -e`. 

Thanks for a great library!

**Comment by 3noch** [comment]
> Thanks for a great library!

Much agreed!

**Comment by Gabriel439** [comment]
`AbstractFilePath` wouldn't solve the problem you describe.  It's mainly to solve the problem of getting `turtle` off the deprecated `system-filepath` library while still preserving the distinction between `FilePath` and `Text`/`String`.

`FilePath`s will always be a little bit painful and the explicit conversion serves mainly to encourage you think about what are the contents of the thing you are converting and whether or not it's safe to treat it as something of the opposite type.

**Comment by 3noch** [comment]
One possibility would be to somehow augment the type of `proc`'s list arguments to accept file paths directly. I do not know what would be involved with that... Likely something not pretty.

**Comment by PierreR** [comment]
Servant has a type class [`ToText`](http://haskell-servant.github.io/servant/Servant-Common-Text.html). I have been wondering for a while why this solution is so uncommon.

**Comment by Gabriel439** [comment]
I'm guessing it's because you can derive `Show` but you can't derive `ToText` so most people just use `Data.Text.pack . show` (i.e. `repr`)

**Comment by PierreR** [comment]
But it is still less efficient, isn't ? 
I mean if I have a data type and then seek for a Text representation (because this is what I use everywhere), I will go by an intermediary String and then pack each time.
This would be avoid with a `derive Text` but I guess it won't happen unless Text has been included in base. Do you know why this is not happening ?

**Comment by PierreR** [comment]
What would be the drawback of changing the signature of `proc` (and `shell) into
```
    :: (MonadIO io,  ConvertibleStrings cs)
    => cs
    -- ^ Command
    -> [Text]
    -- ^ Arguments
    -> Shell Text
    -- ^ Lines of standard input
    -> io ExitCode
```

**Comment by PierreR** [comment]
So after a bit of research `ToText` does not exist anymore in `Servant` ... See https://github.com/haskell-servant/servant/commit/40d2c688975cd638aa05fa6abc4736adbe04b8ef

I guess there is a real danger to expose such a general type class in a specific library. Am I right to believe such a type class should go into the `text` package or not exist at all (at least with such a general name). And I would guess it is not in `text` because `text` is not in `base`.

**Comment by Gabriel439** [comment]
@PierreR Yeah, if there were such a type class it would belong in the `text` library.  Actually, there is a type class that is pretty similar in spirit which is the `Buildable` type class provided by the `text-format` library.  That's even  more preferable since `Builder`s will be even more efficient.  I'm not sure why it's in the `text-format` library instead of `text`, though.

However, there's still one last thing that you would need, which is a way to derive `Buildable` for types that derive `Generic` to give behavior equivalent in power to `Show`.

**Comment by Gabriel439** [comment]
One follup comment: so it looks like `printf` won't work because you don't know ahead of time how many arguments the `format` function will take.  `printf = echo . format` only works if the format string takes no arguments.  There's also no way to bypass the `format` function and define `printf` directly in terms of the internals exposed by the `Format` type because of the way it is currently implemented.  You would have to make the `Format` type a bit more complex to support both `format` and `printf`.

However, I can still implement the a format specifier for `UTCTime`, upon which I will mark this issue fixed.  The general verbosity of `FilePath`/`Text` conversions won't go away because `turtle` will always insist on keeping the two types separate.  Technically, even if we used the Prelude `FilePath` you'd still have to convert because the Prelude `FilePath` is `String` which is not the same as `Text`.

The request for exception-throwing subprocess runners will be subsumed by issue #121.
