### ISSUE TITLE
printf decimal with precision

### ISSUE THREAD

**Issue by miguel-negrao** [Gabriel439/Haskell-Turtle-Library#136]
Would be nice to able to format decimals stating the precision and the zero padding char. For now I'm importing Text.Printf but that outputs strings, which then requires conversions from and to Text.

**Comment by Gabriel439** [comment]
The main issue here is that to capture the full range of `printf` functionality you would need five parameters:

* whether to left or right align
* whether to include sign for positive numbers
* whether to pad with zeros or spaces
* the width of the field
* the precision

... and at that point you're better off just formatting it outside of the `Format` DSL since it would be too verbose to include inline within a format string.

However, if you need something a bit higher quality than `Text.Printf` I recommend the `text-format` library which outputs `Text` instead of `String`.  You could then use that to build your own custom format specifiers on the fly, like this:

```haskell
n :: Format r (Int -> r)
n = makeFormat (\n -> Data.Text.Format.format "{}" (left 8 ' ' (prec 3 n)))
```

**Comment by miguel-negrao** [comment]
Ok, will switch to text-format. Might be useful to add a line somewhere in the formatting part of the tutorial suggesting the use of text-format for more complex formatting needs.

**Comment by Gabriel439** [comment]
I updated the tutorial to mention `text-format` in 0ae1bd34ec7c3b8f4663d90de712f9c5daaf7f4c
