### ISSUE TITLE
No way to capture stdout, stderr and exitcode

### ISSUE THREAD

**Issue by lspitzner** [Gabriel439/Haskell-Turtle-Library#139]
`inshellWithErr`/`inprocWithErr` are stdout and stderr; `procStrict`/`shellStrict` are stdout and exitCode.

It is not documented if the former throw some exception if the exitcode is not 0, but i would assume not (?). So maybe there is _some_ way.

Also, the param documentation of `inprocWithErr` and `inshellWithErr` does not mention stderr, which had me confused, because i searched for stderr on the haddock.

**Comment by Gabriel439** [comment]
They do not throw an exception, but in retrospect they probably should since there is no other way to communicate the `ExitCode` anyway using the `Shell` type.  Would it be alright with you if I modified them to throw an exception on non-zero exit code?  I'd probably mark this as a breaking API change and document it in the haddocks and changelog.

I'll also fix the documentation for the parameters.

**Comment by lspitzner** [comment]
The exception would be raised as part of running the shell via `sh` or `view`, right? maybe it would make sense to simply return the exit code in addition to the folded value?

I don't mind the breaking change, as I fell back on `System.Process.readProcessWithExitCode` for now, but there may very well be people expecting the current behaviour, especially given that they asked for stderr capturing to begin with (nonempty stderr and nonzero exitcode are related, i'd guess.)

**Comment by Gabriel439** [comment]
There is no way to return the exit code if the result is a `Stream`

Also, nonempty `stderr` does not necessarily imply a non-zero exit code.  However, I'll still be cautious and avoid changing the current behavior to avoid any surprises for end users.  For now I'll just document the fact that it does not throw an exception if there is a non-zero exit code.

**Comment by lspitzner** [comment]
> Also, nonempty stderr does not necessarily imply a non-zero exit code.
Certainly; i just meant that there might be some correlation.

The new documentation is clear.

Thanks for the quick response and for making the package in the first place.

**Comment by Gabriel439** [comment]
You're welcome! :)

**Comment by maoe** [comment]
I'm also thinking about this now.

Basically I'd like to grep through stdout but without having to throw away the command status. We could of course write a function like `streams` as opposed to `stream`, which throws an exception but we need to copy and paste tens lines of code. This is because there's no way to catch exceptions in the `Shell` monad. If there were something like `catch :: Exception e => Shell a -> (e -> Shell a) -> Shell a`, then we could avoid the code duplication:

```haskell
stream :: Process.CreateProcess -> Shell Text -> Shell Text
stream p s = streams p s `catch` (\(SomeProcessException _) -> empty)
```
assuming `SomeProcessException` is the root exception type of `ShellFailed` and `ProcFailed`, and `streams` throws one of them depending on the `cmdspec`.

**Comment by Gabriel439** [comment]
@maoe The lack of `throw` and `catch` for `Shell` is intentional, because as far as I know there's no way to simultaneously satisfy the `Monad` laws and the `throw`/`catch` laws for `Shell`.

To explain why, let me first recap the `Monad` laws:

```haskell
return x >>= f = f x

m >>= return = m

(m >>= f) >>= g = m >>= (\x -> f x -> g)
```

If you replace `(>>=)` with `catch` and replace `return` with `throw` you get the corresponding `throw`/`catch` laws:

```haskell
throw e `catch` f = f e

m `catch` throw = m

(m `catch` f) `catch` g = m `catch` (\x -> f x `catch` g)
```

The conflict that I'm referring to is that you can't simultaneously satisfy the following two laws for the `Shell` type:

```haskell
return x >>= f = f x

throw e `catch` f = f e
```

To see why, let's look at the obvious implementation of `catch` for `Shell`:

```haskell
catch
    :: Exception e
    => Shell a
    -> (e -> Shell a)
    -> Shell a
catch m f = Shell (\fold -> _foldIO m fold `catch` (\e -> _foldIO (f e) fold))
```

This definition of `catch` is nice because it does satisfy the associativity law for `catch` (proof omitted):

```haskell
(m `catch` f) `catch` g = m `catch` (\x -> f x `catch` g)
```

So far so good!

Now let's try to implement `throw`.  One way to implement `throw` is to just defer to the `throwIO` for `IO`:

```haskell
throw :: Exception e => e -> Shell a
throw e = liftIO (throwIO e)
```

The problem with this definition is that it does not satisfy this law:

```haskell
throw e `catch` f = f e
```

Here's why:

```haskell
throw e `catch` f
= liftIO (throwIO e)
= (\(FoldM step begin done) -> do
    x  <- begin
    a  <- throwIO e
    x' <- step x a
    done x' ) `catch` f
= (\(FoldM _ begin _) -> do
    x  <- begin
    throwIO e ) `catch` f

/= f e
```

... which is not necessarily the same thing as `f e`, since `begin` may have side effects and might even throw exceptions of its own.

So one possible way to fix this is to change the definition of `throw` to just ignore the `Fold` supplied to the shell:

```haskell
throw :: Exception e => e -> Shell a
throw e = Shell (\_ -> throwIO e)
```

That does satisfy the `throw e `catch` f = f e` law, but now it violates the monad law:

```haskell
return x >>= f = f x
```

Here's why:

```haskell
return e >>= throw
= Shell (\(FoldM step0 begin0 done0) -> do
    x  <- begin0
    x' <- _foldIO (throw e) (FoldM step0 (return x) return)
    done0 x' )
= Shell (\(FoldM _ begin0 done0) -> do
    x  <- begin0
    x' <- throwIO e
    done0 x' )
= Shell (\(FoldM _ begin0 _) -> do
    x  <- begin0
    throwIO e )
= Shell (\(FoldM _ begin0 _) -> do
    x  <- begin0
    throwIO e )

/= throw e
```

... which is not the same as `throw e` because it also runs the `begin0` action which may have side effects or throw exceptions of its own.

There's no way to fix this conflict between the two laws unless there's a different way to implement `throw` or `catch` that I'm not aware of.

That's why I omit `throw` and `catch` for `Shell` since no matter how you implement it the user will run into subtle semantic bugs with the fold's `begin` function being run the wrong number of times.

**Comment by sgraf812** [comment]
Correct me if I'm wrong, but this isn't really fixed yet, right?

I'd really like to be able to have all 3 things, and I'm willing to pay by strictness for it. So, I need something like `shellStrict`/`procStrict` which also gives me back `stderr` instead of letting the called process pollute the log. For now I'm just calling `readProcessWithExitCode` directly, which is obviously a little hackish, if not unsafe.

**Comment by Gabriel439** [comment]
Oops!  I just read the text of the question and not the title.  You're right that this is not fixed yet
