### ISSUE TITLE
Support full functionality of common command-line utils

### ISSUE THREAD

**Issue by nkaretnikov** [Gabriel439/Haskell-Turtle-Library#156]
Only a couple programmers on my team know Haskell, but most can deal with Bash. I started writing something in Bash, but when it stopped being trivial, I decided to give turtle a try.  I wanted to make it easier for non-Haskellers to read my code, so I decided to keep the new version as close as possible to the Bash one. Unfortunately, that proved difficult because `cut` from turtle doesn't work like `cut` from Bash. At least I couldn't figure out how to concisely express `cut -f1`. So, are there any plans to aim for 100% compatibility with the common utils, or should I start looking for a different lib?

P.S. Yes, I could probably define a helper for that, but these little helpers add up making the Haskell code look complicated for beginners.

**Comment by Gabriel439** [comment]
So for `cut` specifically, the way I would structure it to resemble Bash is something like this:

```haskell
cut :: ([Text] -> [Text]) -> Shell Text -> Shell Text
cut k = fmap (Data.Text.unwords . k . Data.Text.words)

f :: Int -> [Text] -> [Text]
f n ws = if n < length ws then [ws !! n] else []
```

Then you could write:

```haskell
>>> cut (f 1) (input file)  -- Get the second column
...
>>> cut (f 1 <> f 3) (input file)  -- Get the second and fourth column
...
```

You should feel free to request me to add additional helpers to `turtle` like `cut`!  If a Unix utility doesn't exist in `turtle`, it's probably just because I forgot to add it, not because I don't want it.

**Comment by nkaretnikov** [comment]
@Gabriel439 Thanks for the prompt reply! `cut` already exists in turtle: https://hackage.haskell.org/package/turtle-1.2.8/docs/Turtle-Prelude.html. I intended my question to be seen in a more general light: are you aiming for turtle to be a drop-in replacement for Bash or not?

**Comment by Gabriel439** [comment]
Turtle aims to be reasonably close to Bash idioms and utilities, but departing from them if there's a better solution than the Bash approach, where "better" usually means either:

* simpler (i.e. eliminating Bash cruft)
* more powerful
* more strongly typed

I actually forgot that I had already added a different version of `cut`, but now I remember why I wrote it that way.  The intention was that the user would something like:

```haskell
example = do
    line <- input file
    let tokens = cut spaces1 line
    return (tokens !! 1, tokens !! 3)
```

My reasoning for doing things this way was that:

* This made it easier for the user to select the delimiter they want to cut on by specifying a pattern in a form that's more powerful than the original `cut` command
* This didn't automatically combine the extracted tokens since the user might want to combine them into something more strongly typed than a line of `Text` (like a tuple, in the above example)

So this is an example of me deviating from the Bash behavior because there's a more powerful and more strongly typed solution

**Comment by nkaretnikov** [comment]
Okay, makes sense to me. I'm closing this issue, but feel free to reopen if you want it open for whatever reason.
