### ISSUE TITLE
Add `toTextIgnore`

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Turtle-Library#16]
I think it would be convenient to add the [shelly `toTextIgnore`](http://hackage.haskell.org/package/shelly-1.6.0/docs/src/Shelly-Base.html#toTextIgnore) function.

**Comment by Gabriel439** [comment]
So I was planning on doing something like this anyway because I would like to create a `Format` specifier for filepaths of this type:

```haskell
fp :: Format r (FilePath -> r)
```

... so that a user could embed `FilePath`s in their format strings.  That would require doing what `toTextIgnore` does anyway.

So anyway, my only request is that it has a shorter name.  Whatever the name is, it just has to be shorter than `format fp`, otherwise I would just ask people to use `format fp` to get this behavior.

**Comment by PierreR** [comment]
Is it too much of a stretch not to expose 'toText' from `Filesystem.Path.CurrentOS` and expose a silent version with the same name ?

**Comment by Gabriel439** [comment]
I prefer a different name.  I'm not worried about breaking backwards compatibility; my actual concern is just avoiding confusion since it would have the same name as an existing function with very similar behavior.

**Comment by PierreR** [comment]
I will play it safe and just add `fp` in `Turtle.Format`
```
{-| `Format` a `Filesystem.Path.CurrentOS` into `Text`
-}
fp :: Format r (FilePath -> r)
fp = makeFormat (\fpath -> either id id (toText fpath))
```
This actually solves my use case. I guess we can expose the function later (if it useful for somebody).

Would you accept this PR ?

**Comment by Gabriel439** [comment]
Yeah, I will accept that
