### ISSUE TITLE
How to use ls? Could it be made easier?

### ISSUE THREAD

**Issue by dogweather** [Gabriel439/Haskell-Turtle-Library#168]
I'm a Haskell beginner, and was following the Turtle tutorial. Part-way through the section on Ghci, I spontaneously tried `ls`, but couldn't see how to use it:

* `ls`
* `ls pwd`
* `ls <$> pwd`
* `ls "."`

...these all failed for typing reasons of one kind or another.

**Comment by lspitzner** [comment]
`ls "."` is close, but you need `view`.
> `view (ls ".")`
> `pwd >>= \path -> view (ls path)`

both work (mind `-XOverloadedStrings`). the [tutorial has a detailed introduction.](https://hackage.haskell.org/package/turtle-1.2.8/docs/Turtle-Tutorial.html#g:9)

**Comment by codygman** [comment]
Keep in mind most turtle functions essentially return a stream. View is a
way of consuming that stream and giving the result.

**Comment by Gabriel439** [comment]
@lspitzner gave the correct answer: enable `OverloadedStrings` and use `view`.  I just want to expand on that to explain why the other versions didn't work:

### Why `ls` didn't work

`ls` doesn't work because you gave it no arguments.  The type error you got probably looked something like this:

```haskell
>>> ls

<interactive>:4:1:
    No instance for (Show (Turtle.FilePath -> Shell Turtle.FilePath))
      (maybe you haven't applied enough arguments to a function?)
      arising from a use of ‘print’
    In a stmt of an interactive GHCi command: print it
```

The reason for the type error is that `ghci` does something like the following algorithm for every command you enter:

* If the expression you entered is of type `IO a`, for some arbitrary type `a`, then run the `IO` action and then:
    * Don't print the result if the type `a` is actually `()`
    * `print` its result if the type `a` implements `Show`
    * `print` nothing if the type `a` does not implement `Show`
* Otherwise, `print` the result of the expression

In this case, the type of `ls` is `FilePath -> Shell FilePath`, which is not of the shape `IO a`, so `ghci` tries to `print` it.

`print` expects that its argument implements the `Show` interface, but something of type `FilePath -> Shell FilePath` does not implement the `Show` interface because functions are not `Show`able.  This in turn leads to the error message you saw:

```
    No instance for (Show (Turtle.FilePath -> Shell Turtle.FilePath))
```

### Why `ls pwd` doesn't work

This doesn't work because `ls` expects a `FilePath` but you gave it a subroutine that returns a `FilePath` (i.e. `IO FilePath`).  To make an analogy to ordinary Bash programming, this would be like running:

```bash
$ ls pwd
ls: pwd: No such file or directory
```

... which gives the wrong behavior because `pwd` is the name of a command and not the name of a file.

In `bash`, the way you would work around this is to do something like this:

```bash
$ DIR=$(pwd)
$ ls $DIR
```

... and the `turtle` analog of that is:

```haskell
main = do
    dir <- pwd
    view (ls dir)
```

Now let's revisit the type error you got, which was this:

```
<interactive>:5:4:
    Couldn't match expected type ‘Turtle.FilePath’
                with actual type ‘io0 Turtle.FilePath’
    In the first argument of ‘ls’, namely ‘pwd’
    In the expression: ls pwd
```

The compiler arrived that this error by first checking the type of `ls`, which is this:

```haskell
ls :: FilePath -> Shell FilePath
```

... and then checking the type of `pwd`:

```haskell
pwd :: MonadIO io => io FilePath
```

... and then comparing the type of `pwd` with the type of the argument to `ls`.  The compiler then notices that the types don't match:

```haskell
ls  ::               FilePath -> Shell FilePath
                     ^
                     | These don't match
                     v
pwd :: MonadIO io => io FilePath
```

... which is what the compiler means when it says that:

```
    Couldn't match expected type ‘Turtle.FilePath’
                with actual type ‘io0 Turtle.FilePath’
```

### Why `ls <$> pwd` doesn't work

This is actually not a type error, but when you ran it nothing happened.  To see why, let's ask the compiler what the type of the expression is:

```haskell
>>> :type ls <$> pwd
ls <$> pwd :: MonadIO io => io (Shell Turtle.FilePath)
```

This is a subroutine whose return result is a stream (or `Shell` in turtle parlance).  In order to view this stream you would have to do something like this:

```haskell
>>> streamOfFiles <- ls <$> pwd
>>> view streamOfFiles
...
...
```

If we revisit `ghci`'s rules for what to print:

* If the expression you entered is of type `IO a`, for some arbitrary type `a`, then run the `IO` action and then:
    * Don't print the result if the type `a` is actually `()`
    * `print` its result if the type `a` implements `Show`
    * `print` nothing if the type `a` does not implement `Show`
* Otherwise, `print` the result of the expression

... we'll see that `ghci` doesn't print the `Shell FilePath` returned by `ls <$> pwd` because the `Shell` type does not implement `Show`.  However, the return value is still *there* even if `ghci` can't print it for you.  That's why we're able to store the return value in the `streamOfFiles` variable and then `view` it to see the actual contents.

Note that this code:

```haskell
example1 = do
    streamOfFiles <- ls <$> pwd
    view streamOfFiles
```

... and this code:

```haskell
example2 = do
    dir <- pwd
    view (ls dir)
```

... do the exact same thing.  In fact, they are guaranteed to do the same thing thanks to the `Monad` laws.

### Why `ls "."` doesn't work

This fails for the same reason as the previous example: `ls "."` is a `Shell FilePath`, but `ghci` cannot `print` a `Shell FilePath` because it does not implement `Show`.  However, you got a different result this time: a type error!

```haskell
>>> ls "."

<interactive>:10:1:
    No instance for (Show (Shell Turtle.FilePath))
      arising from a use of ‘print’
    In a stmt of an interactive GHCi command: print it
```

This is again due to `ghci`'s rules for how to print things:

* If the expression you entered is of type `IO a`, for some arbitrary type `a`, then run the `IO` action and then:
    * Don't print the result if the type `a` is actually `()`
    * `print` its result if the type `a` implements `Show`
    * `print` nothing if the type `a` does not implement `Show`
* Otherwise, `print` the result of the expression

Notice how `ghci` behaves differently if the value is pure versus the result of an `IO` action.  In our previous example (`ls <$> pwd`) the un-`Show`able value was the result of an `IO` action so it was silently ignored.  However, if the un-`Show`able value is pure then it's a type error instead.  It's confusing, I know!

In this case the resolution is the same: you can display the stream using `view`.

If you want to better build an intuition for these sorts of things I recommend reading the [`Turtle.Tutorial`](https://hackage.haskell.org/package/turtle-1.2.8/docs/Turtle-Tutorial.html) which explains these same concepts in more detail.

**Comment by Gabriel439** [comment]
I'll go ahead and close this since I believe the question was answered, but if you have any additional concerns feel free to reopen this
