### ISSUE TITLE
type error in Turtle.Tutorial

### ISSUE THREAD

**Issue by samkimhis** [Gabriel439/Haskell-Turtle-Library#207]
In version 1.3.0, it is said that `print x = echo (repr x)` can be implemented, but it gives a type error; `echo` expects `Line` but `repr` returns `Text`. Should it be revised to `print x = echo (unsafeTextToLine (repr x))` for completeness' sake?

**Comment by int-index** [comment]
Somehow I missed this one while updating the documentation (I thought I checked every example in GHCi).

Yes, the example should be updated, but certainly not with `unsafeTextToLine`. There were a few complaints that `echo` is inconvenient because it accepts a `Line`, this looks like another instance of the problem.

The man page for the `echo` utility says:

> echo - display a line of text

but I had no problem running `echo "Hello\nWorld"` (in bash) on my machine. Would it be better for Turtle's `echo` to accept `Line`, `Text`, or both (using a type-class for polymorphism)? I don't know.

**Comment by Gabriel439** [comment]
I think that we may consider reverting `echo` to accept `Text` and I'd be fine with a breaking version change if that's what we agree on

**Comment by int-index** [comment]
The downside to making `echo` accept `Text` is that to output a line one would need to apply `lineToText`, which is too verbose (not good for scripting).

I don't have a strong opinion on this.

**Comment by Gabriel439** [comment]
Another thing to consider is that if people auto-generated `Show` instances (as they should) then the `Show` instance would not have any newlines.  So that would imply that the type of `repr` really should be:

```
repr :: Show a => a -> Line
```

However, in practice there are custom `Show` instances that may have newlines

I'll have to think about this some more, but my initial reaction is that the current type signature of `echo` is probably the right one and the fact that the user has to use `unsafeLineToText` forces the user to consider that they may be dealing with a non-standard `Show` instance.

**Comment by Gabriel439** [comment]
Actually, another idea is to generalize the type of `repr`:

```haskell
repr :: (Show a, IsString text) => a -> text
```

Then `print = echo . repr` would type-check

**Comment by PierreR** [comment]
> I'll have to think about this some more, but my initial reaction is that the current type signature of echo is probably the right one and the fact that the user has to use unsafeLineToText

Something else to consider is the fact that there isn't any `optLine` in Turtle.Options. Is this on purpose ? I end up having to convert between `Text` and `Line` so much that it has become a burden.

**Comment by Gabriel439** [comment]
In addition to the immediate fix to this issue that generalized the type of `repr` I also added a patch to provide string formatters and command-line option parsers for `Line`s in 405625b75da00a48465eb8bf9ed4dc86529edd1b to fix the issue that @PierreR commented on
