### ISSUE TITLE
Using FilePath with `(<>)` is error prone

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Turtle-Library#214]
The current FilePath integration with `(<>)` is troublesome and error prone:

```
eclipseVersion = "4.5"

let fp = "foo" </> "bar_" <> eclipseVersion </> "plugin" -> foo/bar_/4.5/plugin 
```

AFAIK most Haskell libraries would use `</>` to automatically insert the path separator but won't do the same with `(<>)`. 

Is this because  `(</>`) and `(<>)` are synonyms in the deprecated ` system-filepath` package ? (see #54)

**Comment by Gabriel439** [comment]
The mental model for working with `FilePath` is that it is not a string and is instead a list of strings (one per path component), and `fromString` creates a file path that is one component long.  So what you are doing is essentially equivalent to:

```haskell
let eclipseVersion = [ "4.5" ]

let fp = [ "foo" ] <> [ "bar_" ] <> eclipseVersion <> [ "plugin" ]
```

... which reduces to:

```haskell
[ "foo", "bar_", "4.5", "plugin" ]
```

However, I agree that this is surprising behavior because I believe that any type that implements both `Monoid` and `IsString` should obey the following two laws:

```haskell
fromString (x <> y) = fromString x <> fromString y

fromString mempty = mempty
```

... which `FilePath` doesn't

Unfortunately, this won't be fixed until there is a better `system-filepath` alternative

**Comment by PierreR** [comment]
As a note, another behavior that will quietly introduce bug in turtle code is the following : 

```
let first = "/home/vagrant" :: FilePath
     second = "/plugin"
     test = first <> second -- "/plugin"
```
If I understand the logic, in practice it makes it so easy to introduce bugs in scripts.
