### ISSUE TITLE
Sdtdout buffering issue when piping (for instance tee) a turtle script

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Turtle-Library#217]
I am not sure this is a `Turtle` problem but I have realized that I am unable to get the buffering output right as soon as I append `| tee last_run.log` to a turtle script.

 So If I have a turtle script called 'test':
```
# Good
> test
printout of a shell/proc command
printout_1 from the main turtle script (for instance with `printf`)
printout of another shell/proc command
printout_2 from the main turtle script (for instance with `printf`)

# Wrong
> test | tee last_run.log
printout of a shell/proc command
printout of another shell/proc command
printout_1 from the main turtle script (for instance with `printf`)
printout_2 from the main turtle script (for instance with `printf`)
```
Is there any trick to get the correct output to survive after appending a `|`. I actually have the exact same problem when I ran a script inside a `Vagrantfile`. I can't get the stdout correct from there.

I have tried different 'incantations' using `stdbuf -i0 -o0 -e0` but without success.

**Comment by PierreR** [comment]
I find a way to make it work by using `script last_run.log -c 'test'`

**Comment by PierreR** [comment]
Another way to fix this is to use `runghc` (I was using compile script) and force LineBuffering like so : 
```
main = do
  System.hSetBuffering System.stdout System.LineBuffering
```
I might be missing something but I find it surprising that turtle does not enforce LineBuffering with `printf` somehow. I don't see why you would want to run a turtle script without LineBuffering on ?

**Comment by Gabriel439** [comment]
It's very uncommon for libraries like `turtle` to specify buffering for you.  Usually the Haskell program author is supposed to specify what buffering they require for their application at the top level the way you did with `System.IO.hSetBuffering`.  If the user doesn't specify which buffering they prefer then the standard library has some heuristics to decide whether or not to use `LineBuffering` or `BlockBuffering`.  For example, if the output goes to an interactive terminal then the standard library picks `LineBuffering` by default and if the output goes to another non-interactive program (like `tee`) then the standard library picks `BlockBuffering` by default.

The reason the standard library doesn't always pick `LineBuffering` is because `BlockBuffering` is more efficient and therefore more suitable for batch programs that emit a lot of output.  The default settings assume that if your program's output is being forwarded to another program that you must be running the program in batch mode and therefore you want to optimize for throughput instead of latency.

The problem you describe is not unique to Haskell programs: the standard libraries of other languages usually do the same thing and there are lots of programs written in other languages that exhibit the same behavior: they use block buffering when piped to another program and line buffering when used interactively within a terminal.  This `tee` issue is a very common one in the Unix world as you can see in questions like this:

http://stackoverflow.com/questions/11337041/force-line-buffering-of-stdout-when-piping-to-tee

You'll see that one of the answers to that question recommends the same resolution: to use `script -c`

**Comment by PierreR** [comment]
Thanks for the detailed answer.

**Comment by Gabriel439** [comment]
You're welcome!
