### ISSUE TITLE
Provide a `Format` specifier for `Line`

### ISSUE THREAD

**Issue by Gabriel439** [Gabriel439/Haskell-Turtle-Library#219]
This will make it easier to format text using `Line`s.  I think it would be as simple as:

```haskell
ln :: Format r (Line -> r)
ln = makeFormat lineToText
```

**Comment by mitchellwrosen** [comment]
`ln` is also a unix utility!

**Comment by Gabriel439** [comment]
Oh yeah!  Good catch :)

Maybe either `l` or `line`, then

**Comment by 3noch** [comment]
`l` is also `1` in many fonts! ;)

**Comment by Gabriel439** [comment]
`line` it is, then! :)

**Comment by 3noch** [comment]
Great. You could also take some styling tips from `sine` which became `sin` and go with `lin`. ;)

**Comment by PierreR** [comment]
`lin` might be more handy because it will avoid conflict with `line` from `ansi-wl-print` that is commonly used without prefixing.

**Comment by int-index** [comment]
Many other formatters are one-letter, I think `l` would be a good choice for `Line`.

> `l` is also `1` in many fonts! ;)

Programmers don't use those fonts. Also, in editors with syntax highlighting numeric literals are usually of a different color than names.

And since there's no `Num` instance for Format, any accidental mistake will be caught by the compiler.

I vote for `l`.

**Comment by 3noch** [comment]
@int-index Good point.

**Comment by Gabriel439** [comment]
In that case I will probably go with `l` then.  I'll put up a pull request

**Comment by Gabriel439** [comment]
Whoops.  Apparently I already added this about a month ago and forgot about it: https://github.com/Gabriel439/Haskell-Turtle-Library/commit/405625b75da00a48465eb8bf9ed4dc86529edd1b#diff-a226812929d307afd57cb2bfa2fe56bb
