### ISSUE TITLE
The Fold and FoldM docs don't link to the foldl package

### ISSUE THREAD

**Issue by mightybyte** [Gabriel439/Haskell-Turtle-Library#220]
The turtle docs for these types aren't useful.  The useful docs reside in the foldl package, but it was very difficult to figure that out.

**Comment by Gabriel439** [comment]
So the issue here is that if you re-export a type (like how `Fold` is re-exported in the `Turtle` module) then `haddock` prefers to link to the local package's re-export instead of the original package

One thing I could do is add documentation pointing to the `foldl` haddocks so that users can figure out how to use `Fold`/`FoldM` more effectively, but I was wondering where the most discoverable place to do that would be

**Comment by mightybyte** [comment]
Yet another argument against re-exports.  :)

In all seriousness, I'd put it in the haddock comment for Shell.

**Comment by Gabriel439** [comment]
Actually, looking at this more closely, the "Folds" section of the tutorial does link to the `Control.Foldl` module, so that seems like a reasonably discoverable place

**Comment by mightybyte** [comment]
It's discoverable if you go through the tutorial.  But not very discoverable for me browsing the haddocks.  It's up to you though.

**Comment by Gabriel439** [comment]
Yeah, I think the tutorial is the appropriate place to reference the `foldl` library
