### ISSUE TITLE
sed drops empty lines, e.g. `sed ("D" *> return "C")`

### ISSUE THREAD

**Issue by dirkz** [Gabriel439/Haskell-Turtle-Library#229]
Using sed drops empty lines, e.g. `sed ("D" *> return "C")`

Version: [1.3.1 from lts-8.3](https://www.stackage.org/lts-8.3/package/turtle-1.3.1)

The following example will omit all empty lines (`Line ""`) from the output. I would expect them to be unaffected.

```haskell
hgLogRewrite = do
  let lines = inproc "hg" ["log"] empty
  lines2 <- sed ("D" *> return "C") lines
  return lines2
```

**Comment by Gabriel439** [comment]
I can reproduce this and found the problem.  This is a regression introduced in `turtle-1.3.0` in the switch from `Text` to `Line` due to the fact that `textToLines ""` returns `[]` instead of `[""]`

@int-index: My intuition here is that the root problem is that `textToLines` should not follow the behavior of `Data.Text.lines`, which behaves inconsistently.  For example:

```haskell
>>> Data.Text.lines "\na\na"
["","a","a"]
>>> Data.Text.lines "\na"
["","a"]
>>> Data.Text.lines ""
[]
```

Instead, it should behave like `Data.Text.splitOn "\n"`, which is internally consistent:

```haskell
>>> Data.Text.splitOn "\n" "\na\na"
["","a","a"]
>>> Data.Text.splitOn "\n" "\na"
["","a"]
>>> Data.Text.splitOn "\n" ""
[""]
```

Here's another example of where `Data.Text.splitOn "\n"` behaves more consistently than `Data.Text.lines`:

```haskell
>>> Data.Text.lines "aa"
["aa"]
>>> Data.Text.lines "a"
["a"]
>>> Data.Text.lines ""
[]
>>> Data.Text.splitOn "\n" "aa"
["aa"]
>>> Data.Text.splitOn "\n" "a"
["a"]
>>> Data.Text.splitOn "\n" ""
[""]
```

If nobody objects I will fix this by changing the behavior of `textToLines` (which `sed` internally uses), which should in turn fix this problem

**Comment by int-index** [comment]
@Gabriel439 Yes, let's change the behavior and also make the return type `NonEmpty Line`.

**Comment by Gabriel439** [comment]
Oh yeah, using `NonEmpty` is a good idea.  Thanks for the tip! :)

**Comment by int-index** [comment]
One thing to keep in mind that we want `select (textToLines s)` to work. Does this mean that `select` should now accept any `Foldable`?

**Comment by Gabriel439** [comment]
Yes, I plan on generalizing the type of `select` to `Foldable` as part of this change
