### ISSUE TITLE
The documentation for `searchable` is misleading

### ISSUE THREAD

**Issue by gelisam** [Gabriel439/Haskell-Turtle-Library#246]
The documentation for `writable` is simply "+w", and as the `chmod` documentation explains, Turtle's `chmod writable "foo.txt"` is the same as Bash's `chmod u+w foo.txt`.

The documentation for `searchable` is simply "+s", so one would conclude that Turtle's `chmod searchable "foo.txt"` is the same as Bash's `chmod u+s foo.txt`, but that it not the case.

    🐢> output "foo.txt" empty
    🐢> shells "ls -l foo.txt" empty
    -rw-r--r-- 1 gelisam staff 0 Jul 14 10:29 foo.txt

    🐢> chmod searchable "foo.txt"
    Permissions {readable = True, writable = True, executable = False, searchable = True}
    🐢> shells "ls -l foo.txt" empty
    -rwxr--r-- 1 gelisam staff 0 Jul 14 10:29 foo.txt

    🐢> shells "chmod u+s foo.txt" empty
    🐢> shells "ls -l foo.txt" empty
    -rwsr--r-- 1 gelisam staff 0 Jul 14 10:29 foo.txt

Note how `ls -l` says `rwx` after `chmod searchable "foo.txt"` but `rws` after `chmod u+s foo.txt`, because the "searchable" bit, whatever that is, is not the same as the setuid bit.

So what would be a better documentation? What does this "searchable" bit mean?

    🐢> chmod searchable "foo.txt"
    Permissions {readable = True, writable = True, executable = True, searchable = True}
    🐢> getmod "foo.txt"
    Permissions {readable = True, writable = True, executable = True, searchable = False}

    🐢> mkdir "foo"
    🐢> output "foo/bar.txt" "abc"

    🐢> chmod rws "foo"
    Permissions {readable = True, writable = True, executable = False, searchable = True}
    🐢> stdout (input "foo/bar.txt")
    abc
    🐢> view (ls "foo")
    FilePath "foo/bar.txt"

    🐢> chmod rwo "foo"
    Permissions {readable = True, writable = True, executable = False, searchable = False}
    🐢> stdout (input "foo/bar.txt")
    *** Exception: foo/bar.txt: openFile: permission denied (Permission denied)
    🐢> view (ls "foo")
    FilePath "foo/bar.txt"

    🐢> chmod nonreadable "foo"  -- ows
    Permissions {readable = False, writable = True, executable = False, searchable = True}
    🐢> stdout (input "foo/bar.txt")
    abc
    🐢> view (ls "foo")

    🐢> chmod owo "foo"
    Permissions {readable = False, writable = True, executable = False, searchable = False}
    🐢> stdout (input "foo/bar.txt")
    *** Exception: foo/bar.txt: openFile: permission denied (Permission denied)
    🐢> view (ls "foo")

According to the above experiments (ran on macOS), I believe a more helpful documentation for those permissions would be:

> `readable`: For files, determines whether reading from that file using `input` will succeed or throw an exception. For directories, determines whether `ls` will stream the true list of files it contains or will silently return an empty list. Abbreviated as `+r` below.
> 
> `writable`:  For files, determines whether writing to that file using `output` will succeed or throw an exception. For directories, determines whether using `output` to create a new file in that directory will succeed or throw an exception. Abbreviated as `+w` below.
> 
> `executable`: For files, determines whether executing that file using `proc` will succeed or throw an exception. Has no effect on directories. Abbreviated as `+x` below.
> 
> `searchable`: For directories, determines whether reading a file from that directory using `input` will succeed or throw an exception. Has no effect on files. Abbreviated as `+s` below, but note that this is unrelated to `chmod u+s`.

**Comment by Gabriel439** [comment]
Yeah, the `+s` in the documentation is incorrect and should also be `+x`

So looking into this more the root of the problem is that `System.Directory`'s model does not match `chmod`'s model.  In `chmod` `+x` means executable for files and searchable for directories, but `System.Directory` uses two separate fields to track executable versus searchable.  Moreover, `System.Directory` has the problem that it doesn't make invalid states unrepresentable.  Specifically, `System.Directory` lets you:

* set both executable and searchable (which is always invalid even according to its own model because it only considers files executable and directories searchable)
* set executable on a directory
* set searchable on a file

Really, the right thing to do is to just get rid of searchable and exclusively use executable for both files and directories for consistency with `chmod`, but I'll still keep it to avoid unnecessary breakage.

So I agree with your proposed documentation, except with one difference: I propose not using `+s` and instead qualifying each `+x` with whether or not it is intended to be used on files or directories.  In other words, `searchable`'s documentation would have `+x (for directories)` and `executable`'s documentation would have `+x (for files)`.  Same thing for the `rws`/`rwx`-style utilities

**Comment by Gabriel439** [comment]
Actually, I realized that perhaps I should use `+s` and clarify that it's not the same as `chmod`'s `+s`, otherwise names like `oos` won't make sense.  Alternatively, perhaps I should just get rid of searchable and support `executable` exclusively.  I'm kind of leaning towards the latter, even if it is a breaking change

**Comment by Gabriel439** [comment]
Also, I checked and under the hood `searchable` and `executable` are treated exactly the same when setting permissions:

```haskell
setAccessPermissions :: FilePath -> Permissions -> IO ()
setAccessPermissions path (Permissions r w e s) = do
  m <- getFileMetadata path
  setFileMode path (modifyBit (e || s) Posix.ownerExecuteMode .
                    modifyBit w Posix.ownerWriteMode .
                    modifyBit r Posix.ownerReadMode .
                    modeFromMetadata $ m)
  where
    modifyBit :: Bool -> Posix.FileMode -> Posix.FileMode -> Posix.FileMode
    modifyBit False b m = m .&. complement b
    modifyBit True  b m = m .|. b
```

They both translate to the executable bit, so there's no loss in power if we just eliminate `searchable` from the API

However, that still leaves the issue of getting permissions.  If we reuse the same `Permissions` type from `System.Directory` then users will get separate `executable` and searchable `flags` whenever they retrieve permissions.  If I remove the `searchable` stuff then I need to create a `turtle`-specific `Permissions` type which only has a single `executable` field that subsumes the old `executable` and `searchable` fields

**Comment by Gabriel439** [comment]
I put up a pull request with one possible solution: https://github.com/Gabriel439/Haskell-Turtle-Library/pull/247
