### ISSUE TITLE
`find` doesn't support "." or ".."

### ISSUE THREAD

**Issue by 3noch** [Gabriel439/Haskell-Turtle-Library#25]
I'm on Windows, so this might be Windows-specific. Observe:

```bash
> pwd
FilePath "C:\\Users\\Elliot Cameron\\Desktop"
> view $ find (some anyChar *> ".JPG") "."
*** Exception: getPermissions: does not exist (No such file or directory)
> view $ find (some anyChar *> ".JPG") "./ScrapBook"
....lots of results....
```

The same behavior occurs with `".."`.

As an aside, is that the easiest way to match against `"*.JPG"`?

**Comment by Gabriel439** [comment]
This is a limitation of the `system-filepath` library since `turtle` reuses the `FilePath` type from that library and its corresponding `IsString` instance, which does not interpret `"."`.  I wouldn't be able to fix that without providing a wrapper of my own around that type, but I'm reluctant to do so because I would like to promote interoperability with other libraries that use the `FilePath` type.

However, you could file an issue against the `system-filepath` library and ask the author if they would be willing to change how `FilePath` interprets `"."`.  It seems pretty inconsistent that they correctly interpret `"./ScrapBook"` but not `"."`.

Also, the easiest way to match against `*.JPG` is to use the `suffix` combinator, which does exactly what you wrote:

```
suffix :: Pattern a -> Pattern a
suffix p = star dot *> p
```

... so then you could just write `suffix ".JPG"`.  Actually the behavior differs slightly from what you wrote because you use `some` instead of `star`.

**Comment by Gabriel439** [comment]
It's also worth pointing out that `find` is a very thin wrapper around `lstree`.  You can extract the file extension much more reliably by taking advantage of `system-filepath`'s built-in `extension` utility:

```haskell
allJpgs dir = do
    file       <- lstree dir
    Just "jpg" <- return (extension file)
    return file
```

**Comment by Gabriel439** [comment]
Or even more direct, you could use `hasExtension`:

```haskell
allJpgs dir = do
    file <- lstree dir
    guard (hasExtension file "jpg")
    return file
```

**Comment by 3noch** [comment]
I'm not able to determine what is exactly wrong with `system-filepath`. Naive testing seems to show that it supports `"."`.

```bash
Prelude Turtle> directory "."
FilePath ".\\"
Prelude Turtle> relative "."
True
Prelude Turtle> root "."
FilePath ""
```

**Comment by Gabriel439** [comment]
Oops, the error is on my end.  The issue is that I'm not canonicalizing the path that I feed to my `ls` algorithm.  This is probably what causes the issue.

**Comment by 3noch** [comment]
Thanks for looking into it.

**Comment by Gabriel439** [comment]
Okay, so I've been testing this on Windows, and I think I've identified the problem, which is a little subtle.

The first issue is that `getPermissions` (but not other commands) fails if the directory has a trailing slash:

```
>>> System.Directory.getPermissions "."
Permissions {readable = True,...}
>>> realpath "."
"C:\\Users\\Gabriel\\proj\\turtle\\"
>>> System.Directory.getDirectoryContents "C:\\Users\\Gabriel\\proj\\turtle\\"
["turtle.cabal","test","src",...]
>>> System.Directory.getPermissions "C:\\Users\\Gabriel\\proj\\turtle\\"
*** Exception: getPermissions: does not exist (No such file or directory)
>>> System.Directory.getPermissions "C:\\Users\\Gabriel\\proj\\turtle"
Permissions {readable = True,...}
```

The second issue is that `encodeString` (which `ls` uses internally) adds a trailing slash to `"."` and `".."`, but not other directories:

```
>>> Filesystem.Path.CurrentOS.encodeString "."
".\\"
>>> Filesystem.Path.CurrentOS.encodeString ".."
"..\\"
>>> Filesystem.Path.CurrentOS.encodeString "src"
"src"
```

This is the reason the command selectively fails on those two special directories.  It also means that this command would fail if you passed in a path with an explicit trailing slash, too, like `"src/"`.

The solution is to remove the trailing slash and I'll submit a fix soon.

**Comment by 3noch** [comment]
Yuck, sounds like something else also needs a bugfix.
