### ISSUE TITLE
No way to run a command with a terminal

### ISSUE THREAD

**Issue by deepfire** [Gabriel439/Haskell-Turtle-Library#29]
Sometimes one may desire to provide a terminal for the command, for  example for
providing a shell to the user, or to have colorized command output.

Apparently this requires jumping through PTY-related hoops which Turtle doesn't do yet.

**Comment by Gabriel439** [comment]
Are you using `shell`/`proc` or `inshell`/`inproc`?  The reason I ask is that `shell`/`proc` don't mess with the command's output at all and forward it along to `stdout`/`stderr` blindly.  They actually don't even do the forwarding themselves: they are just a thin wrapper around `System.Process` and they say to just let the external process inherit the current `stdout` and `stderr` handle.

However, in the case of `inshell`/`inproc` there is a very good chance that they could munge the output because they convert it to lines of `Text` and then use `text` utilities to print these lines.

**Comment by deepfire** [comment]
Gabriel, that's what I tried:

```
main :: IO ()
main = do
  _ <- T.shell (pack "/bin/sh") T.stdin
  return ()
```

I didn't even get it to interact with me..

**Comment by deepfire** [comment]
On the other hand, it's promising, since the following preserves the colors (and hence, the PTY access):

```
main :: IO ()
main = do
  _ <- T.shell (pack "ls --color=auto") T.stdin
  return ()
```

**Comment by Gabriel439** [comment]
For the `/bin/sh` example, try compiling the program with the `-threaded` flag and let me know if it works or not.  There might be an initial delay of a few seconds before it displays the first prompt.

**Comment by deepfire** [comment]
Gabriel, that's what I re-tried the `/bin/sh` example with:
```
ghc -threaded --make Build.hs -rtsopts -with-rtsopts=-I0 -outputdir=${shakedir} -o ${shakedir}/build && ${shakedir}/build
```
Alas, it didn't change anything..

**Comment by Gabriel439** [comment]
I was able to reproduce this on my end.  At this point, the only thing I can suggest is to try using the raw `process` API, specifically the `createProcess` command and see if there is some permutation of options that gets this to work.

If not, then it may be that the only solution is to essentially figure out how to fix the `process` library or reimplement it.

**Comment by lspitzner** [comment]
I can confirm this works with the `process` API, i.e.

~~~~
[lspitzner testsandbox]$ cabal exec -- ghci
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
Prelude> import System.Process
Prelude System.Process> runProcess "bash" [] Nothing Nothing Nothing Nothing Nothing >>= waitForProcess 
[lspitzner testsandbox]$ ps
  PID TTY          TIME CMD
 6169 pts/41   00:00:00 cabal
 6177 pts/41   00:00:00 ghc
 6554 pts/41   00:00:00 bash
 7074 pts/41   00:00:00 ps
31358 pts/41   00:00:00 bash
[lspitzner testsandbox]$ exit
exit
ExitSuccess
Prelude System.Process> 
~~~~

**Comment by Gabriel439** [comment]
So it seems like the key difference between `System.Process.runProcess` and `Turtle.{proc,shell}` is that the former inherits `stdin` from the current process whereas the latter does not (it is piped in through another handle).

Probably an easy solution to this problem is to export the underlying `system`/`systemStrict`/`stream`/`streamWithErr` functions, except not have them make any changes to the supplied `CreateProcess` (and instead push those changes downstream into `proc`/`shell`/`procStrict`/...).  Then you could pass in your own `CreateProcess` with all handles set to `Inherit` to get the desired behavior.

How does that sound?

**Comment by Gabriel439** [comment]
So I ended up being conservative and just exporting `system` for now, which lets you supply an arbitrary `CreateProcess` so that you can access the full power of the underlying `process` library.  That should be able to solve this specific problem as @lspitzner shows that you can fix this using `runProcess` (which is in turn implemented internally in terms of the `CreateProcess` API)

**Comment by deepfire** [comment]
@Gabriel439, do you think the manual should include an example for that?

**Comment by Gabriel439** [comment]
I opened a PR to add this to the FAQ: https://github.com/Gabriel439/Haskell-Turtle-Library/pull/244

**Comment by srghma** [comment]
another possible option

```
  -- exec is a functionality of an operating system that runs an executable file in the context of an already existing process, replacing the previous executable
  -- https://en.wikipedia.org/wiki/Exec_(system_call)
  System.Posix.Process.executeFile "sh" True args' Nothing
```
