### ISSUE TITLE
Does it make sense to instance Num Shell?

### ISSUE THREAD

**Issue by Profpatsch** [Gabriel439/Haskell-Turtle-Library#43]
I’m fixing build warnings atm and noticed that there is

``` haskell
instance Monoid a => Num (Shell a) where
    fromInteger n = select (replicate (fromInteger n) mempty)

    (+) = (<|>)
    (*) = (<>)
```

It’s missing `abs`, `signum` and `-`. Do these even make sense?
And if not, why instance it at all. To make it more beginner-friendly? But then again that reminds me of C++ Operator Overloading.

**Comment by Profpatsch** [comment]
It still compiles w/o the instance at least.

**Comment by Profpatsch** [comment]
Same with `Pattern`.

**Comment by Gabriel439** [comment]
It's because `Shell`s form a semiring, but Haskell has no semiring class an `Num` is the closest approximation

Same thing for `Pattern`

**Comment by Profpatsch** [comment]
Hah, I see. More abstract algebra I should remember from university. :P

**Comment by Profpatsch** [comment]
How about using https://hackage.haskell.org/package/semiring-simple-0.2.1.0/docs/Data-Semiring.html ?

**Comment by Gabriel439** [comment]
The biggest issue with that package is the use of overlapping instances like:

```haskell
    instance Semiring a => Monoid a where
```

That will conflict with every `Monoid` instance, even for types that do not implement `Semiring` (unless Haskell has changed its typeclass resolution behavior since the last time I checked).

The second reason is that you lose support for overloaded numeric literals if you use the `Semiring` class.  I like being able to do things like:

```
>>> view (3 * "Example)
"Example"
"Example"
"Example"
```

**Comment by Profpatsch** [comment]
Ah, so it’s best to use the builtins.

**Comment by Gabriel439** [comment]
Is this still an issue for you?

**Comment by Profpatsch** [comment]
Nope.
