### ISSUE TITLE
Unexpected `spaces1` behaviour

### ISSUE THREAD

**Issue by xged** [Gabriel439/Haskell-Turtle-Library#62]
λ> stdout $ input "t.txt"
    ()
    main =
    λ> stdout $ sed (spaces1 *> "main" *> return "foo") "()\nmain ="
    ()foo =
    λ> stdout $ sed (spaces1 *> "main" *> return "foo") $ input "t.txt"
    ()
    main =
I was expecting last output to be `()foo =`

**Comment by Gabriel439** [comment]
If you give `sed` a `Shell Text`, `sed` will only do substitutions within each `Text` element that the stream yields and `sed` will not do substitutions across multiple `Text` values.

That means that when you provide `input "t.txt"` the `sed` command sees two isolated `Text` values: `"()"` and `"main ="` (one value for each line of input from "t.txt").  The `sed` command does not see the newline separator since the `input` utility removes the newlines when splitting the file into lines.  That means that there is no substitution since there is no whitespace before `main` in `"main ="`.

Note that there is no requirement that each element of a `Shell Text` is one line.  Splitting by lines is purely a convention adopted by utilities like `input`.  If you create a synthetic stream of your own you can split it along any arbitrary text boundaries if you want to.

That's why your first `sed` example worked because the `sed` command sees a stream with just one `Text` element: `"()\nmain ="`.

Also, you could simplify your first `sed` example to this:

```haskell
stdout $ sed ((spaces1 *> "main") *> return "foo") "()\nmain ="
```

**Comment by xged** [comment]
Is that a desired behavior? Does `input` split lines, so to achieve *streaming* (if I correctly understand the term/feature)? And what is the solution to the *unrecognized new-line problem* would be?

**Comment by Gabriel439** [comment]
Yes, `input` splits lines to stream the file contents.

If you want to read in the entire file's contents as a single uninterrupted string, use the `strict` utility:

```haskell
strict (input "t.txt") :: IO Text
```

**Comment by Gabriel439** [comment]
I will go ahead and mark this issue closed unless you have any additional questions.
