### ISSUE TITLE
Feature request: whole word pattern

### ISSUE THREAD

**Issue by xged** [Gabriel439/Haskell-Turtle-Library#64]
grep --word-regexp:

    Select  only  those  lines containing matches that form whole words.  The
    test is that the matching substring must either be at  the  beginning  of
    the line, or preceded by a non-word constituent character.  Similarly, it
    must be either at  the  end  of  the  line  or  followed  by  a  non-word
    constituent  character.  Word-constituent characters are letters, digits,
    and the underscore.
Especially when you cannot do `spaces1 *> pattern *> spaces1` without `strict` #62

**Comment by Gabriel439** [comment]
I think in this case the only solution is to introduce a synthetic space at the beginning of the line before matching:

```haskell
example = do
    line <- input "t.txt"
    _:_  <- return (match (spaces1 *> pattern *> spaces1) (" " <> line)
    return line
```

The problem is that there is no `Pattern` that you can use to detect if you're at the beginning of the input.  The reason why is that `Pattern`s do not store consumed input.

I could modify how `Pattern` works so that it does store consumed input and then the solution would be more elegant because you could use a `begin` combinator:

```haskell
-- | Match the beginning of input
begin :: Pattern ()
```

... like this:

```haskell
(begin <|> spaces1) *> pattern *> (eof <|> spaces1)
```

Give me some more time to think about it.

**Comment by xged** [comment]
What about `prefix` & `suffix`?
` :: Pattern a -> Pattern a  -- Defined in ‘Turtle.Pattern’`

**Comment by Gabriel439** [comment]
So I gave this more thought and I decided not to implement this.  I decided to err on the side of keeping the implementation of `Pattern` simple, even if that means that it is missing a few features.
