### ISSUE TITLE
Understanding internals; pattern-matching wild-cards list

### ISSUE THREAD

**Issue by xged** [Gabriel439/Haskell-Turtle-Library#65]
What does the 3rd line do?

    grep pattern s = do
        txt <- s
        _:_ <- return (match pattern txt)
        return txt

**Comment by Gabriel439** [comment]
In Haskel, if you pattern match on the result of a bind and the pattern match fails it will call the `fail` function.  You can think of the above code as equivalent to:

```haskell
grep pattern s = do
    txt <- s
    case match pattern txt of
        _:_ -> return txt
        _   -> fail "<some compiler-generated error message>"
```

`fail` is a method of the `Monad` type class and for `Shell`, the behavior of `fail` is equivalent to `empty`:

    fail _ = empty

... so the code reduces further to:

```haskell
grep pattern s = do
    txt <- s
    case match pattern txt of
        _:_ -> return txt
        _   -> empty
```

So you can read that as saying that `grep` loops over every `Text` output of `s` and if the pattern matches the `Text` then `grep` will output the `Text` value (using `return`), otherwise `grep` will discard the `Text` value (using `empty`)
