### ISSUE TITLE
Style: What order functions have in file's layout?

### ISSUE THREAD

**Issue by xged** [Gabriel439/Haskell-Turtle-Library#76]
Besides categories I do not see much

**Comment by Gabriel439** [comment]
There's no hard rule.  I just organize things in whatever way I think will be easier for the user to browse.

For `Turtle.Prelude` specifically I just organize things from simpler types to more complex types, with the exception of the `chmod` section which I put at the bottom since it's very large and would obstruct more important utilities if I put it near the top.
