### ISSUE TITLE
Escaped quotes disappear in "inshell"

### ISSUE THREAD

**Issue by AlexeyRaga** [Gabriel439/Haskell-Turtle-Library#78]
Here is an example:

    λ: stdout $ inproc "echo" ["\"test\"", "aa"] empty
    "test" aa
    λ: stdout $ inshell "echo \"test\" aa" empty
    test aa

the double quotes disappear in the later case, single quotes behave similarly.

This works, however:
    
    λ: stdout $ inshell "echo \\\"test\\\" aa" empty
    "test" aa

Which is a bit noisy and counter-intuitive.

**Comment by Gabriel439** [comment]
The reason for the difference is that `inshell` interprets the string using `bash` but `inproc` bypasses `bash` completely and instead uses `execvp` to directly forward the arguments unmodified to the given executable.  The `bash` interpreter is what was removing the quotes from your `inshell` example, which you can verify by running the command directly within your shell:

```bash
$ echo "test" aa
test aa
```

This is why `inproc` preserves your double quotation marks because now there is no intermediate `bash` interpreter that will tamper with your arguments.  This is the intended behavior of `inproc` (to skip the bash `interpreter`, which can be insecure).

**Comment by AlexeyRaga** [comment]
I can see the point, but I use Turtle to get away from Bash ;)
It is just from the me-writing-haskell perspective it is a bit inconvenient that I cannot have an escaped text value and then just use it in different places without thinking about how it was escaped and was it escaped enough to be used in a particular place.

**Comment by 3noch** [comment]
By using `inshell` you are not getting away from bash. ;) That's the point.

**Comment by Gabriel439** [comment]
Yes, what @3noch said.  `inshell` uses the Bash interpreter.  If you want to get away from Bash's weird treatment of quotation marks, use `inproc` instead, since `inproc` preserves quotation marks (and all other symbols) perfectly.
