### ISSUE TITLE
`sed` `prefix` removes the whole line

### ISSUE THREAD

**Issue by xged** [Gabriel439/Haskell-Turtle-Library#81]
func :: Text -> IO ()
    func s = stdout $ sed (prefix (text s) *> "") $ input "test.hs"

`func` drops lines containing `s`, instead of `s` itself

**Comment by Gabriel439** [comment]
The way `sed` works is that it replaces the matched pattern with the return value of the `Pattern`.  I'll explain how you can deduce what your pattern returns.

First, the return value of:

```haskell
m *> n
```

... is whatever the return value of `n` is.  You can tell this from the type of `(*>)`:

```haskell
-- This discards the left argument's return value and keeps the right argument's return value
(*>) :: Pattern a -> Pattern b -> Pattern b
```

Since your pattern was `prefix (text s) *> ""`, that means that whatever the right argument returns (i.e. the `""`) will be what the `sed` replaces the match with.

The pattern `""` is syntactic sugar for `text ""`, which means that it matches the empty string and then returns the empty string as its result.  This means that whatever your pattern matches gets replaced with the empty string.  This is why `func` deleted all lines that matched the pattern.

This might not be what you intended.  If you can explain the desired substitution  I can show you how to translate it into the equivalent `Pattern`.

**Comment by xged** [comment]
I expected `func` to delete all occurrences of `s` (ones that are at the beginning of the line) rather then all lines that contains `s`

Eg `func_ s = stdout $ sed (s *> "") $ input "test.hs"` does delete all occurrences of `s` rather then all lines that contains `s`

**Comment by xged** [comment]
Well, the behavior is understandable by looking at the definition of `prefix`. I guess I will just wait for #64.
