### ISSUE TITLE
`liftShell :: ([a] -> [b]) -> Shell a -> Shell b` ?

### ISSUE THREAD

**Issue by xged** [Gabriel439/Haskell-Turtle-Library#85]
liftShell :: ([a] -> [b]) -> Shell a -> Shell b
    liftShell f s = select =<< f <$> fold s Fold.list

(*Shelly* has `liftSh :: ([a] -> [b]) -> Sh a -> Sh b`)

Another similar one:

    liftShellIO :: MonadIO io => (Text -> a) -> Shell Text -> io a
    liftShellIO = liftIO . fmap f . strict

**Comment by Gabriel439** [comment]
The reason I don't have functions like these is that they materialize the entire stream.  I generally try to avoid exposing functions that materialize the entire stream unless absolutely necessary.  My philosophy is to make the inefficient path verbose in order to gently encourage the user to do the efficient thing.

**Comment by Gabriel439** [comment]
I'm marking this closed mainly because I'd prefer not to add these to the default API.  If the user wants strictness they need to explicitly use the `strict` or `Fold.list` utilities to highlight that they want that behavior.
