### ISSUE TITLE
Mentioning stack in tutorial

### ISSUE THREAD

**Issue by phadej** [Gabriel439/Haskell-Turtle-Library#89]
What you think about mentioning stack in the tutorial? https://github.com/commercialhaskell/stack/wiki/Script-interpreter

**Comment by Gabriel439** [comment]
I am totally for it!

**Comment by int-index** [comment]
A link to the wiki page would be sufficient, I think. `stack` is a separate tool, I wouldn't want to read about it in a library tutorial.

**Comment by phadej** [comment]
@int-index there are different ways to run turtle scripts already discussed in http://hackage.haskell.org/package/turtle-1.2.0/docs/Turtle-Tutorial.html If it only could be possible to succinctly explain to new haskellers, why installing `turtle` (or any other library) globally (for user or system), might be a bad idea in the long run.

**Comment by int-index** [comment]
@phadej Oh, it also mentions the Haskell Platform... which I personally quite dislike. So if we mention `stack` *instead* of Haskell Platform and not as an alternative option, I think it'll be a change for the better.

**Comment by Gabriel439** [comment]
I will add a little more detail than just a link because I anticipate `stack`-driven `turtle` scripts being a significant driver for `turtle` adoption (I specifically requested this feature and example)

One of the biggest pieces of feedback that I get from potential `turtle` users is that Haskell is not installed by default on most systems (compared to `python` and `bash`, which are `turtle`'s natural competitors) and providing users with a way to ensure that the Haskell interpreter and `turtle` package are installed correctly in a single line is a big deal to those users.

I also agree that we should remove references to the Haskell Platform.

**Comment by phadej** [comment]
@Gabriel439 I totally agree, `turtle` could be a gateway into the Haskell.

**Comment by Gabriel439** [comment]
Alright, I have a pull request up to update all the `turtle` examples to use `stack` and it works quite well.  The only example that doesn't work under `stack` is loading an existing file using `stack ghci`, but it wasn't a huge loss.  Take a look at #91 and let me know if it is what you had in mind

**Comment by Gabriel439** [comment]
Fixed by #91

**Comment by phadej** [comment]
Sorry, totally forgot to look into the patch. It looks great. The only "issue", is which resolver to use. Maybe the default (= not specified) would be an option too?

**Comment by Gabriel439** [comment]
I didn't even realize you could omit it.  I just tested that it works, so I'll just remove the resolver flags from the examples
