### ISSUE TITLE
Getting exit codes from forked shells (is this the idiomatic way?)

### ISSUE THREAD

**Issue by duplode** [Gabriel439/Haskell-Turtle-Library#92]
I am writing a simple script which mostly consists of commands ran with `shell` and sequenced with `(.&&.)`. One of those commands is a `git push`. Since that will ask for my GitHub passphrase, I used `fork`, `with` and `wait` to run it recovering the exit code:
``` haskell
.&&. with (fork $ shell "git push gh master" "") wait
```
It works fine. However, given that `with` is not brought into scope by `import Turtle` (an `import Control.Monad.Managed` is necessary), I wonder if I am overlooking a better or more idiomatic way to do that.

**Comment by Gabriel439** [comment]
Actually, I should probably just generalize the type of `(.&&.)` to:

```haskell
(.&&.) :: Monad m => m ExitCode -> m ExitCode -> m ExitCode
```

There's nothing `IO`-specific about its internal implementation.  Then you would be able to use that within a `Managed` block before you call `runManaged`.

So technically there is nothing wrong with using the `with` operation (I also use it from time to time).  The main reason that I don't export it by default is that I try to encourage users to consume the value they are producing directly within `runManaged` or `sh`, like this:

```haskell
-- This assumes that the type of `(.&&.)` has been generalized to any `Monad`
example = runManaged (do
    let forked :: Managed ExitCode
        forked = do
            a <- fork (shell "git push gh master" [] empty)
            liftIO (wait a)
    exitCode <- something .&&. forked
    ... -- Use `exitCode` here )
```

Generally, `with` is safe to use if you are returning a value from the `Managed` block that is not one of the values that will be automatically finalized.  For example, this is safe:

```haskell
safeExample :: IO Text
safeExample = with (readonly "input.txt") (\handle -> strict (inhandle handle))
```

... because the `Text` returned won't be finalized.  However, this is not safe:

```haskell
unsafeExample :: IO Handle
unsafeExample = with (readonly "input.txt") return
```

... because the `Handle` returned by that will be finalized before you can use it.

With some advanced type tricks you can actually enforce in the types that `Managed` resources don't leak, but I chose to just go with a simpler approach and not export `with` by default.  This requires the user to at least think twice about whether they are returning something that might be finalized when the `Managed` computation is over.  Importing the `with` function is basically the user's way of saying "I know what I'm doing".

So that's a long-winded way of saying that what you are doing is totally safe.

**Comment by duplode** [comment]
Thank you. In the end, I guess I'll still need `with` or some other way to get an overall result value (e.g. `using` and `fold`), as I massage the script into an `IO ExitCode` which is consumed by another library. In any case, generalising `(.&&.)` and `(.||.)` would be nice - their restricted types were a were bit surprising when reading the docs, though it doesn't really affect me for the moment (as I said, my script is basically a chain of `shell` invocations).

**Comment by Gabriel439** [comment]
Actually, on second though I should probably add `with` anyway to make `turtle` more approachable for people who come from a Python scripting background

**Comment by Gabriel439** [comment]
I did both fixes: `turtle` now exports `with` and I generalized the types of `(.&&.)` and `(.||)`.

**Comment by duplode** [comment]
Neat, thanks :+1:
